import type { Metadata } from "next";
import { ThemeProvider } from "./shared/providers";
import "./globals.css";
import { Navbar } from "./shared/components";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-mono'>
        <ThemeProvider
          defaultTheme="system"
          attribute="class"
          enableSystem
          enableColorScheme
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
